name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - joblib=0.14.1
  - jpeg=9b
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.3
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - pthread-stubs=0.3
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.3.1
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=46.4.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.4.2
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7

